### ISSUE TITLE
No Bind Option

### ISSUE THREAD

**Issue by craighl4** [Rexeh/joystick-diagrams#13]
It would be great to have an option so that "NO BIND" appearing on the exported diagram is optional.  Makes it easier to see what you actually have bound and what is available for binding.

Otherwise this tool is awesome.  So much easier than filling out PDF templates.

**Comment by Rexeh** [comment]
Thanks Craig, this seems like a fair request and something I had planned to do, this can serve as the feature ticket.

**Comment by Rexeh** [comment]
Moved to release 1.3 - Can be overridden in classes (for v1.2) but placing with this requirement of settings menu/persistence

**Comment by Rexeh** [comment]
Added in 1.3, via config file for time being
