### ISSUE TITLE
Throttle Button Missing

### ISSUE THREAD

**Issue by craighl4** [Rexeh/joystick-diagrams#14]
Button number 33 is missing from the CM2 throttle.  It is located at the bottom of the right throttle axis.

**Comment by Rexeh** [comment]
Thanks Craig, you are right indeed, I didn't even know my throttle had this button until someone pointed it out!!

Will add to list of items with new templates

**Comment by craighl4** [comment]
The number of buttons on that throttle is crazy.  I can't imagine ever needing their button box but I will no doubt get one anyway.

**Comment by Rexeh** [comment]
Closed for now, fixed in 1.2 but will create a new template in time.
