### ISSUE TITLE
Star Citizen - Game Support

### ISSUE THREAD

**Issue by Rexeh** [Rexeh/joystick-diagrams#27]
# Feature
Enable the ability to directly use Star Citizen configs to produce joystick templates.

# Items Needed
- Game data structure - C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\USER\Controls\Mappings
- Example config files - [cw_103.zip](https://github.com/Rexeh/joystick-diagrams/files/5366991/cw_103.zip)

# Planned
1.3 Release

**Comment by JDLuke** [comment]
Rexeh, I am a software developer (not a Python guy but it seems readable enough) and Star Citizen player.  If there's any assistance I can provide with this please let me know.

In the meanwhile, https://github.com/JDLuke/starcitizen is my repository for transferring control schemes from machine to machine.  If that HOSAS configuration offers you any benefit please feel free to use it.

**Comment by JDLuke** [comment]
Yeah, I'll help with testing for sure.

**Comment by doerek** [comment]
i exported my controls (hosas - dual tm16000)
[layout_Dual-TM16000_doerek_exported.zip](https://github.com/Rexeh/joystick-diagrams/files/6118166/layout_Dual-TM16000_doerek_exported.zip)

**Comment by Rexeh** [comment]
> i exported my controls (hosas - dual tm16000)
> [layout_Dual-TM16000_doerek_exported.zip](https://github.com/Rexeh/joystick-diagrams/files/6118166/layout_Dual-TM16000_doerek_exported.zip)

Thanks interesting use case, not sure I had considered 2 sticks with same names and same GUIDs.

**Comment by Rexeh** [comment]
Now delivered in 1.4
