### ISSUE TITLE
No template for device even it is supported

### ISSUE THREAD

**Issue by dsanchezseco** [Rexeh/joystick-diagrams#37]
The export proccess returns that there are no templates for the hotas (warbrd+alpha right and throttle mt-50cm2) even when they are supported.

```
Export Started
No Template for: RIGHT VPC Stick WarBRD
No Template for: VPC Throttle MT-50CM2
Export Finished
```

**Comment by Rexeh** [comment]
Thanks @dsanchezseco.

At the moment, the template name must match 100% your VPC device. As such you'll need to make sure these are the same.

My device for example by default is called **VPC Throttle MT-50 CM2**, so you need an .SVG with name "VPC Throttle MT-50 CM2.svg"

If you have LEFT/RIGHT sticks, you'll need to copy the template and have two versions in your /TEMPLATES folder with the relevant names.

Let me know if that solves your issue

**Comment by dsanchezseco** [comment]
yup, that did it. Feel free to close the issue if needed. Thanks!

**Comment by Rexeh** [comment]
No problem!
