### ISSUE TITLE
DCS: Disabled devices cause error

### ISSUE THREAD

**Issue by PatHightree** [Rexeh/joystick-diagrams#42]
Not a big issue, but something I ran into.
I disabled a couple of devices which I'm not using in DCS.
This caused a disabled.lua file to be created in Config/Input and caused the following error after selecting the DCS folder:
Error: [WinError 267] The directory name is invalid: 'C:/Users/patri/Saved Games/DCS\\Config\\Input\\disabled.lua'

I've attached a zip of my config directory for reproduction.
[Config.zip](https://github.com/Rexeh/joystick-diagrams/files/5762411/Config.zip)

**Comment by PatHightree** [comment]
I uninstalled the unused devices and removed the disabled.lua file.
DCS keeps recreating the file with the following contents.

local disabled = {
	["devices"] = {
	},
	["pnp"] = false,
}
return disabled

**Comment by Rexeh** [comment]
Hi thanks,

This one is known issue due to be fixed next version

https://github.com/Rexeh/joystick-diagrams/issues/40

Temporary workaround detailed in above!
