### ISSUE TITLE
Can't work out how to label axis

### ISSUE THREAD

**Issue by jacrify** [Rexeh/joystick-diagrams#56]
Axis on my thrustmaster don't show up as labelled- they just appear as "Axis_RX" etc rather than the labels in Joystick Gremlin. I've tried a few different ways to get them to show up but no luck.

Screenshots and joystick gremlin config (renamed as .txt) attached. Expected behaviour is that instead of "Axis RX" it should show "Fuel Mix" or "Test".

Great piece of work by the way. 

[MicrosoftFlightSim2020 .txt](https://github.com/Rexeh/joystick-diagrams/files/6459477/MicrosoftFlightSim2020.txt)

![image](https://user-images.githubusercontent.com/9527059/117823591-fc312700-b2b0-11eb-93a4-35a2cde25a58.png)

![image](https://user-images.githubusercontent.com/9527059/117823649-0e12ca00-b2b1-11eb-9607-72d8b93bdf2f.png)

**Comment by Rexeh** [comment]
Thanks for this!

Unfortunately not currently supported in current version - https://joystick-diagrams.com/features/

This is due to JG not exposing axis data in the XML, it requires a deeper Integration with windows devices to draw these out. This deeper Integration would come with a future version.

**Comment by Rexeh** [comment]
> Is it possible to just pull in the description nodes if they are present? Eg the stanza from my file was:
> 
> ```
> <axis description="Fuel Mix" id="7">
>                     <container type="basic">
>                         <action-set>
>                             <description description="Test"/>
>                             <remap axis="7" axis-scaling="1.0" axis-type="absolute" vjoy="1"/>
>                         </action-set>
>                     </container>
>                 </axis>
>                 
> ```
> 
> I just want it to say "Fuel Mix" on the diagram. Is the problem that you don't know where on the stick "axis-7" maps to?

Unfortunately not, because there's nothing in there telling me what "AXIS 7" is, I need to query Windows to pull that out and resolve to AXIS_RX and so forth.

**Comment by Rexeh** [comment]
Closed as part of rewrite
