### ISSUE TITLE
Feature Request: Name output files after Joystick Gremlin input file name

### ISSUE THREAD

**Issue by jacrify** [Rexeh/joystick-diagrams#58]
That way if we have multiple profiles in JG they get different names. 

IE input file: MicrosoftFlightSim2020.xml
Output file: JG_MicrosoftFlightSim2020_X52 H.O.T.A.S._Default.svg  ( rather than JG_X52 H.O.T.A.S._Default.svg)

**Comment by Rexeh** [comment]
Ok, so the file name becomes part of it. Seems fair to me if you have multiple files :)

**Comment by Rexeh** [comment]
Closing this as unfortunately doesn't sit with the v2 model, but it will allow various naming/renaming of profiles to do the above eventually!
