### ISSUE TITLE
VKB Space Gunfighter feedback/issues

### ISSUE THREAD

**Issue by Jahfry** [Rexeh/joystick-diagrams#64]
I'm using dual VKB Space (Kosmosima) Premium (ie, has ministicks) with Gunfighter (mk2) bases (ie, not the NXT base with added buttons/axes). 

Using this to log some feedback. 

* The sticks for my setup are the same as the VKB Gladiator NXT templates, so I used those
     * Copied the VKB NXT template files to "VKB-Sim Space Gunfighter.svg" (right stick, no "R" at end of name) and "VKB-Sim Space Gunfighter L.svg" (left)
     * The existing templates can be used as-is if the SVG is cropped to remove base image and all buttons/axes from the base (buttons 23-29, throttle axis). Crappy visualization of this is attached as an image

* The NXT diagrams appear to have an error where the buttons on the 4+center hats on the top of the stick are swapped. As in on my sticks what the diagram calls buttons 11-15 are really buttons 6-10 (and vice versa). This COULD be a difference between the NXT and the Kosmosima but I doubt it as the stick portions of these products are the same, it's the bases that differ. 

* On these sticks, if the "Premium" sku, when pressing the mini-stick it switched from an 8-way hat to 2 additional axes (X/Y rot). The diagram gets this mostly right as it shows the assignments to the 8-way hat and shows the "Mode Switch" as the center press for "X/Y Rotation Axis" but does not show what functions the X/Y Rot axes are bound to. 

... Low priority but interesting:

* In Star Citizen, prior to customizing bindings, I applied the "VKB SCG Premium Dual" control profile. Then I saved that out to a .XML and loaded in Diagrams to see the defaults. Doing that shows an odd label on the right stick's far right side button called "Flashui kp 3" and the bottom-front button is "Flashui kp 4". When I rebind this in Star Citizen I get no notification of it being bound to some other function so maybe an artifact of something in the XML that has changed over time? 

![vkb feedback](https://user-images.githubusercontent.com/16520816/157401998-7aacfcea-05e8-4955-b360-20815f659d23.png)

**Comment by Rexeh** [comment]
Closing this in preparation for v2 launch. Old star citizen support had race conditions that randomly assigned button inputs or button modifiers depending on where it was defined. Going forward separate templates can be  had for the same stick with any name to cover all the variants
