### ISSUE TITLE
Add support for VKB NXT Evo diagrams exported from Star Citizen

### ISSUE THREAD

**Issue by dopeghoti** [Rexeh/joystick-diagrams#70]
The sticks are functionally identical, but the device names are different.  I was able to mostly use the exported XML by changing the name of the device from e. g. 

```xml
 <options type="joystick" instance="2" Product=" VKBsim Gladiator EVO  L    {0201231D-0000-0000-0000-504944564944}"/>
```

to

```xml
 <options type="joystick" instance="2" Product=" VKB-Sim Gladiator NXT L   {0201231D-0000-0000-0000-504944564944}"/>
```

However, the throttle, X, Y, and Z axes' bindings to not appear to be properly parsed:

![image](https://user-images.githubusercontent.com/295727/176936446-31185dc9-37a9-4bad-8990-0a5212dd15ec.png)

In my bindings' case, the relevant XML for these bindings are:

```xml
  <action name="v_pitch">
   <rebind input="js3_y"/>
  </action>
  <action name="v_roll">
   <rebind input="js3_x"/>
  </action>
  <action name="v_strafe_lateral">
   <rebind input="js2_x"/>
  </action>
  <action name="v_strafe_longitudinal">
   <rebind input="js2_y"/>
  </action>
  <action name="v_strafe_vertical">
   <rebind input="js2_rotz"/>
  </action>
  <action name="v_yaw">
   <rebind input="js3_rotz"/>
  </action>
```

**Comment by dhartford** [comment]
unable to push PR due to signing requirements, but kept it in my fork for now.

**Comment by Rexeh** [comment]
No reply on merge, so closing this issue.

Issue captured for 2.0 release and SC parser update as GUIDs are now unique within the file, removing previous problems.
