### ISSUE TITLE
T.16000M Joystick Left | Wrong Picture

### ISSUE THREAD

**Issue by doerek** [Rexeh/joystick-diagrams#71]
i just downloaded the last version and it seams that the Template for the "T.16000M Joystick Left" Device shows the wrong Picture.
i edited the file in illustrator and now it shows the right picture
![T 16000M Joystick Left](https://user-images.githubusercontent.com/2093684/187073817-96785528-9c0a-436d-982c-b46f5977e5a4.svg)
e

**Comment by doerek** [comment]
[T.16000M Joystick Left.svg.zip](https://github.com/Rexeh/joystick-diagrams/files/9439642/T.16000M.Joystick.Left.svg.zip)
just to make sure GH dont screws the File up...here is a Ziped version

**Comment by doerek** [comment]
Button 3 & 4 were switched
[T.16000M Joystick Left.svg.zip](https://github.com/Rexeh/joystick-diagrams/files/9481045/T.16000M.Joystick.Left.svg.zip)

**Comment by Rexeh** [comment]
This should be integrated into 2.0
