### ISSUE TITLE
vJoy Devices

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [Rexeh/joystick-diagrams#77]
Hey mate,

unfortunately your String check of the Device Name cuts after "vJoy Device" but the Device has an extended Name, because all vJoy Devices are called the same and only at the End of the Name is an exclusive identifier.

f.e. my Stick is named "vJoy Device {A6E73220-701F-11ed-8002-444553540000}" and the Throttle is named vJoy Device {3DF36BB0-87A5-11ed-8003-444553540000}, so i tried several names for my template (stick and throttle are x-56 rhino) but everything i tried failed, i just get the template for the stick and only if i name the template "vJoy Device" (non-case-sensitiv).

Or am i doing something wrong?

If so i would appreciate some help, but is sincerly think there is a bug.

With Kind Regards
ToastyBanK3nobi

**Comment by Rexeh** [comment]
#51 resolves this, so for now this won't be fixed until that feature is delivered.

**Comment by ToastyBanK3nobi** [comment]
I know, we already talked on Discord ;) sorry forgot to close it here :)

**Comment by Rexeh** [comment]
> I know, we already talked on Discord ;) sorry forgot to close it here :)

No problems at all, I think your issues would be fixed by using guids going forward. Stay on the discord and would love for you to test when available if you're willing :)

**Comment by ToastyBanK3nobi** [comment]
I have no intention of leaving, when you have a build ready to test, feel free to ping me on your Discord or here, i´ll gladly test this -  i have to many planes so i´m in dire need ;) And then i have to figure out how to make a template, cause i use a tripple set of the buttons (as mentioned) ;)
