### ISSUE TITLE
Multiple parent profiles don't merge together

### ISSUE THREAD

**Issue by LoneBoco** [Rexeh/joystick-diagrams#84]
Multiple parent profiles fail to properly merge into a single parent.  It only merges the bottom most parent in the list.

For example, I have this bind (I have shrunken the output but highlighted the entries that have data):
`Spaceship` | `Vehicle` | `Spaceship scanning`

![image](https://github.com/Rexeh/joystick-diagrams/assets/1922821/e2d491a7-1cdf-40af-93f8-4fc8fd57ba4d)

Each of the three profiles has no overlapping keybinds.  If I add the following to the `Spaceship` profile:

![image](https://github.com/Rexeh/joystick-diagrams/assets/1922821/60092921-bcb6-4d82-8069-3adb6f734b64)

It generates the following:

![image](https://github.com/Rexeh/joystick-diagrams/assets/1922821/ef692625-07a2-4b4d-8dd9-fe6205936ad9)

The `Vehicle` binds in the top-left corner are missing.  Only the `Spaceship` and `Spaceship scanning` profiles were merged together.

**Comment by Rexeh** [comment]
Hey @LoneBoco thanks for raising. This does sound unexpected based on what you describe, would you please provide your star citizen file so that it can be debugged?

**Comment by LoneBoco** [comment]
[actionmaps.zip](https://github.com/user-attachments/files/15890740/actionmaps.zip)

There's my actionmaps.xml file.  I believe that is all that is required.

**Comment by Rexeh** [comment]
Sorry for large delay on this.

![image](https://github.com/user-attachments/assets/a3e11ab0-9376-4301-8681-1688754a0c3c)

Think this is what you expected, found the bug and fixed in latest build. Keep eye out for 2.1.0

**Comment by Rexeh** [comment]
Closed, planned to 2.1.0 release
