### ISSUE TITLE
Winwing templates need some modified.

### ISSUE THREAD

**Issue by NidhoggAC** [Rexeh/joystick-diagrams#85]
Hello,

I found Winwing Orion2 Throttle Base templates (maybe in all F-15/F-18 version) in 2.0.9 has some issues:

1. The templates miss Button_112/113 upon on throttle axis. Button_112 on AXIS_RX up and Button_113 on AXIS_RY up.
2. Buttons on AXIS_SLIDER_2 are Button_109~111 (up to down).

The following  picture is orion 2 base with F-15EX throttle key map in SimAppPro.
![winwing orion base 2 key map](https://github.com/user-attachments/assets/6f6938fc-8201-40b1-98f4-40fc7294279c)

The following file is the Orion2 Throttle Base+15EX templates I have modified.
![WINWING Orion Throttle Base II + F15EX HANDLE L + F15EX HANDLE R v1 1](https://github.com/user-attachments/assets/b7230f47-58c5-4a36-9fde-e84138c0bf8c)

Also I add pitch and roll axis for Orion joystick + F-16EX templates. Because this two axis will be identify when export F-4E file but not 
 in other fighter.
![d1df9-WINWING Orion Joystick Base 2 + JGRIP-F16-F-4e-45mc](https://github.com/user-attachments/assets/ed23f2aa-8265-4407-836d-c7881192d832)

Maybe other Orion joystick templates has same situation.

For your reference.

**Comment by Rexeh** [comment]
Hi, thanks for taking the time to report this

It would be better as a pull request if you've already got proposed changes for the template files!
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Happy if you make a PR and link to this issue and can review SVG  changes directly and merge them in :)

Have a nice weekend

**Comment by Rexeh** [comment]
Closed in https://github.com/Rexeh/joystick-diagrams/pull/86
